version: "3"

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8181"
    volumes:
      - ./BD/ImportarDatos:/home
  db:
    image: dbllaves
    environment:
      - MYSQL_ROOT_PASSWORD=secret