version: "2"

services:
  base:
    image: node:12-alpine
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
  install:
    extends:
      service: base
    command: npm run dev
    
  add-dep:
    extends:
      service: base
    command: npm install
  # initial:
  #   extends:
  #     service: base
  #   command: npm init -y

